Fix BatchNorm initialisation
This line inside gernet_s config `norm_layer=partial(BatchNormAct2d, affine=False)` cause many bugs like this: `AttributeError: 'NoneType' object has no attribute 'zero_'`